### ISSUE TITLE
Extend Error

### ISSUE THREAD

**Issue by stevenvachon** [crisson/validation-error#1]
And probably use ES2015 classes to do it cleanly.

**Comment by crisson** [comment]
Is your use case that you want to `throw ValidationError`?  Errors collected by this lib are primarily meant to be returned instead of thrown, with a return type resembling `Validation.<ValidationError, T>` or `Promise.<Validation.<ValidationError, T>>` in the async case.

**Comment by stevenvachon** [comment]
Errors should be thrown.

You could try extending [aggregate-error](https://npmjs.com/aggregate-error).

**Comment by stevenvachon** [comment]
You could try extending [aggregate-error](https://npmjs.com/aggregate-error).

**Comment by crisson** [comment]
I think the library's name has led to some confusion.  Maybe I should have named it `ValidationResult`.  It's meant to be used within the paradigm of converting recoverable errors to data types that are returned instead of thrown.  

Think of Rust's `Result<T, E>` type or `Either[EE, A]` in Scala, where this library would be the `E` or `EE`, respectively.

**Comment by stevenvachon** [comment]
I think this makes sense:
```js
try {
  validateFields({ ... });
} catch (error) {
  if (error instanceof ValidationError) {
    display(error.invalidations);
  } else {
    throw error;
  }
}
```

**Comment by crisson** [comment]
Here's an [example](https://github.com/crisson/validation-example/blob/master/validate.js) of how this library is intended to be used.  Checkout the validate method at the bottom of the file.

**Comment by stevenvachon** [comment]
I guess that we can't agree. It's your library, but "error" implies `Error()`.
